# Generated by Django 5.1.3 on 2024-12-03 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='currency_id',
        ),
    ]
