# Generated by Django 5.1.3 on 2024-12-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_currency_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencyrate',
            unique_together=set(),
        ),
    ]
