# Generated by Django 5.1.3 on 2024-12-05 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_currencyrate_unique_currency_pair'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='currencyrate',
            name='unique_currency_pair',
        ),
    ]
