# Generated by Django 5.1.3 on 2025-02-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_currencyrate_unique_currency_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
